### ISSUE TITLE
Add support for tor-browser

### ISSUE THREAD

**Issue by ihateprogramming88** [unforgivablesin/sandbox_manager#1]
When trying to apply the sandbox manager on fedora asahi Linux, I was unable to create a functional sandbox for Tor browser

Any help will be appreciated 
![image_20241214104933](https://github.com/user-attachments/assets/bd382ad0-ae98-47cb-b1c5-e7575a75daaf)

Not 100% sure what the issue is

**Comment by ihateprogramming88** [comment]
```
> admin@localhost:~$ sandbox-create --app Signal --entry signal-desktop --path /usr/lib64/signal-desktop --dri --pulseaudio --dbus     --seccomp /home/admin/.sandbox_manager/seccomp/signal.bpf --notifications --screencast --dbus-app org.signal.Signal 
> admin@localhost:~$ sandbox-launch --app TorBrowser
> /usr/bin/xdg-dbus-proxy unix:path=/run/user/1000/bus /run/user/1000/xdg-dbus-proxy/org.torbrowser.TorBrowser.sock --own=org.torbrowser.TorBrowser --own=org.torbrowser.TorBrowser.* --talk=org.freedesktop.portal.Notification --talk=org.freedesktop.portal.Screencast
> ------------------
> /bin/bwrap --unshare-ipc --unshare-pid --unshare-uts --unshare-cgroup --unshare-user --new-session --ro-bind-try /etc/ssl/certs/ca-bundle.crt /etc/ssl/certs/ca-bundle.crt --ro-bind-try /etc/ssl/certs/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt --ro-bind-try /etc/resolv.conf /etc/resolv.conf --ro-bind-try /etc/hosts /etc/hosts --ro-bind-try /etc/ld.so.preload /etc/ld.so.preload --ro-bind-try /etc/ld.so.conf /etc/ld.so.conf --ro-bind-try /etc/ld.so.conf /etc/ld.so.conf --ro-bind-try /etc/ld.so.cache /etc/ld.so.cache --ro-bind-try /etc/ld.so.conf.d /etc/ld.so.conf.d --ro-bind-try /etc/fonts /etc/fonts --ro-bind /usr /usr --ro-bind /lib64 /lib64 --ro-bind /lib /lib --ro-bind /usr /usr --ro-bind /proc /proc --ro-bind /dev /dev --tmpfs /var --tmpfs /tmp --tmpfs /run --dir /run/user/1000 --dev /dev --proc /proc --ro-bind /home/admin/Downloads/tor-browser-linux-aarch64-tbb-nightly.2024.12.11/tor-browser /home/admin/Downloads/tor-browser-linux-aarch64-tbb-nightly.2024.12.11/tor-browser --ro-bind-try /etc/resolv.conf /etc/resolv.conf --setenv DISPLAY :0 --ro-bind /run/user/1000/.mutter-Xwaylandauth.C8SLY2 /run/user/1000/.mutter-Xwaylandauth.C8SLY2 --setenv WAYLAND_DISPLAY wayland-0 --setenv XDG_SESSION_TYPE wayland --ro-bind /run/user/1000/wayland-0 /run/user/1000/wayland-0 --bind-try /home/admin/.sandbox_manager/appdata/TorBrowser /home/admin --dev-bind-try /dev/dri /dev/dri --ro-bind-try /sys/devices/pci0000:00 /sys/devices/pci0000:00 --ro-bind-try /sys/dev/char /sys/dev/char --ro-bind-try /run/user/1000/pulse /run/user/1000/pulse --ro-bind /run/user/1000/xdg-dbus-proxy/org.torbrowser.TorBrowser.sock /run/user/1000/bus --ro-bind /var/lib/dbus/machine-id /var/lib/dbus/machine-id --setenv DBUS_SESSION_BUS_ADDRESS unix:path=/run/user/1000/bus --setenv GTK_THEME Adwaita:dark --setenv XDG_DATA_DIRS /home/admin/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/ --bind /home/admin/.config/mimeapps.list /home/admin/.config/mimeapps.list sh -c '"/home/admin/Downloads/tor-browser-linux-aarch64-tbb-nightly.2024.12.11/tor-browser/Browser/start-tor-browser" || ([ !  -x "/home/admin/Downloads/tor-browser-linux-aarch64-tbb-nightly.2024.12.11/tor-browser/Browser/start-tor-browser" ] && "$(dirname "$*")"/Browser/start-tor-browser)' dummy %k 
> ------------------
> Traceback (most recent call last):
>   File "/etc/SandboxManager/launch.py", line 16, in <module>
>     sandbox_launcher(args, argstr)
>     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
>   File "/etc/SandboxManager/src/sandbox.py", line 105, in sandbox_launcher
>     launch_sandbox(binary_cmd=config.cmd,
>     ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
>                    args=argstr,
>                    ^^^^^^^^^^^^
>     ...<4 lines>...
>                    dbus_app=config.dbus_app,
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^
>                    dbus_permissions=config.dbus_permissions)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/etc/SandboxManager/src/launcher.py", line 202, in launch_sandbox
>     subprocess.check_output(f"{command[0]} {args}", shell=True)
>     ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib64/python3.13/subprocess.py", line 472, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>            ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>                **kwargs).stdout
>                ^^^^^^^^^
>   File "/usr/lib64/python3.13/subprocess.py", line 577, in run
>     raise CalledProcessError(retcode, process.args,
>                              output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '/bin/bwrap --unshare-ipc --unshare-pid --unshare-uts --unshare-cgroup --unshare-user --new-session --ro-bind-try /etc/ssl/certs/ca-bundle.crt /etc/ssl/certs/ca-bundle.crt --ro-bind-try /etc/ssl/certs/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt --ro-bind-try /etc/resolv.conf /etc/resolv.conf --ro-bind-try /etc/hosts /etc/hosts --ro-bind-try /etc/ld.so.preload /etc/ld.so.preload --ro-bind-try /etc/ld.so.conf /etc/ld.so.conf --ro-bind-try /etc/ld.so.conf /etc/ld.so.conf --ro-bind-try /etc/ld.so.cache /etc/ld.so.cache --ro-bind-try /etc/ld.so.conf.d /etc/ld.so.conf.d --ro-bind-try /etc/fonts /etc/fonts --ro-bind /usr /usr --ro-bind /lib64 /lib64 --ro-bind /lib /lib --ro-bind /usr /usr --ro-bind /proc /proc --ro-bind /dev /dev --tmpfs /var --tmpfs /tmp --tmpfs /run --dir /run/user/1000 --dev /dev --proc /proc --ro-bind /home/admin/Downloads/tor-browser-linux-aarch64-tbb-nightly.2024.12.11/tor-browser /home/admin/Downloads/tor-browser-linux-aarch64-tbb-nightly.2024.12.11/tor-browser --ro-bind-try /etc/resolv.conf /etc/resolv.conf --setenv DISPLAY :0 --ro-bind /run/user/1000/.mutter-Xwaylandauth.C8SLY2 /run/user/1000/.mutter-Xwaylandauth.C8SLY2 --setenv WAYLAND_DISPLAY wayland-0 --setenv XDG_SESSION_TYPE wayland --ro-bind /run/user/1000/wayland-0 /run/user/1000/wayland-0 --bind-try /home/admin/.sandbox_manager/appdata/TorBrowser /home/admin --dev-bind-try /dev/dri /dev/dri --ro-bind-try /sys/devices/pci0000:00 /sys/devices/pci0000:00 --ro-bind-try /sys/dev/char /sys/dev/char --ro-bind-try /run/user/1000/pulse /run/user/1000/pulse --ro-bind /run/user/1000/xdg-dbus-proxy/org.torbrowser.TorBrowser.sock /run/user/1000/bus --ro-bind /var/lib/dbus/machine-id /var/lib/dbus/machine-id --setenv DBUS_SESSION_BUS_ADDRESS unix:path=/run/user/1000/bus --setenv GTK_THEME Adwaita:dark --setenv XDG_DATA_DIRS /home/admin/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/ --bind /home/admin/.config/mimeapps.list /home/admin/.config/mimeapps.list sh -c '"/home/admin/Downloads/tor-browser-linux-aarch64-tbb-nightly.2024.12.11/tor-browser/Browser/start-tor-browser" || ([ !  -x "/home/admin/Downloads/tor-browser-linux-aarch64-tbb-nightly.2024.12.11/tor-browser/Browser/start-tor-browser" ] && "$(dirname "$*")"/Browser/start-tor-browser)' dummy %k ' returned non-zero exit status 1.
> admin@localhost:~$ 

> 
```
