### ISSUE TITLE
Add support for vs-codium 

### ISSUE THREAD

**Issue by ihateprogramming88** [unforgivablesin/sandbox_manager#2]
I was successfully able to build a sandbox for vs-codium but the functionality was not complete. I keen getting a spawn bin/bash ENOEOT ERROR.

Is there anywaysm to diagnose and fix this?

![20241201_230837_8066247865044888379_20241214140548](https://github.com/user-attachments/assets/62c827e4-93a1-4c7c-ae2b-6a5c13b87b71)

**Comment by unforgivablesin** [comment]
It would be preferred to have the text in the git issue, however can you share the contents of `/usr/share/codium` ? I believe the directory is wrong.

**Comment by ihateprogramming88** [comment]
```
"> admin@localhost:~/.sandbox_manager/seccomp$ sandbox-launch --app Codium
> /usr/bin/xdg-dbus-proxy unix:path=/run/user/1000/bus /run/user/1000/xdg-dbus-proxy/org.codium.Codium.sock --own=org.codium.Codium --own=org.codium.Codium.* --talk=org.freedesktop.portal.Notification --talk=org.freedesktop.portal.Screencast
> ------------------
> /bin/bwrap --unshare-ipc --unshare-pid --unshare-uts --unshare-cgroup --unshare-user --new-session --ro-bind-try /etc/ssl/certs/ca-bundle.crt /etc/ssl/certs/ca-bundle.crt --ro-bind-try /etc/ssl/certs/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt --ro-bind-try /etc/resolv.conf /etc/resolv.conf --ro-bind-try /etc/hosts /etc/hosts --ro-bind-try /etc/ld.so.preload /etc/ld.so.preload --ro-bind-try /etc/ld.so.conf /etc/ld.so.conf --ro-bind-try /etc/ld.so.conf /etc/ld.so.conf --ro-bind-try /etc/ld.so.cache /etc/ld.so.cache --ro-bind-try /etc/ld.so.conf.d /etc/ld.so.conf.d --ro-bind-try /etc/fonts /etc/fonts --ro-bind /usr /usr --ro-bind /lib64 /lib64 --ro-bind /lib /lib --ro-bind /usr /usr --ro-bind /proc /proc --ro-bind /dev /dev --tmpfs /var --tmpfs /tmp --tmpfs /run --dir /run/user/1000 --dev /dev --proc /proc --ro-bind /usr/share/codium /usr/share/codium --ro-bind-try /etc/resolv.conf /etc/resolv.conf --setenv DISPLAY :0 --ro-bind /run/user/1000/.mutter-Xwaylandauth.P8KGY2 /run/user/1000/.mutter-Xwaylandauth.P8KGY2 --setenv WAYLAND_DISPLAY wayland-0 --setenv XDG_SESSION_TYPE wayland --ro-bind /run/user/1000/wayland-0 /run/user/1000/wayland-0 --bind-try /home/admin/.sandbox_manager/appdata/Codium /home/admin --bind-try /home/admin/Downloads /home/admin/Downloads --dev-bind-try /dev/dri /dev/dri --ro-bind-try /sys/devices/pci0000:00 /sys/devices/pci0000:00 --ro-bind-try /sys/dev/char /sys/dev/char --ro-bind-try /run/user/1000/pulse /run/user/1000/pulse --ro-bind /run/user/1000/xdg-dbus-proxy/org.codium.Codium.sock /run/user/1000/bus --ro-bind /var/lib/dbus/machine-id /var/lib/dbus/machine-id --setenv DBUS_SESSION_BUS_ADDRESS unix:path=/run/user/1000/bus --setenv GTK_THEME Adwaita:dark --seccomp 4 --setenv XDG_DATA_DIRS /home/admin/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/ --bind /home/admin/.config/mimeapps.list /home/admin/.config/mimeapps.list /usr/share/codium/codium %F 
> ------------------
> [1:1215/102605.516668:ERROR:content_main_runner_impl.cc(477)] Failed to initialize cpuinfo
> [2:1215/102605.517831:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [5:1215/102605.536553:ERROR:content_main_runner_impl.cc(477)] Failed to initialize cpuinfo
> [2:1215/102605.682559:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [2:1215/102605.682585:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> MESA-LOADER: failed to retrieve device information
> MESA-LOADER: failed to retrieve device information
> MESA-LOADER: failed to retrieve device information
> [2:1215/102605.751360:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [2:1215/102605.751377:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [2:1215/102605.751388:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> MESA-LOADER: failed to retrieve device information
> MESA-LOADER: failed to retrieve device information
> MESA-LOADER: failed to retrieve device information
> [main 2024-12-15T10:26:05.797Z] getUnixShellEnvironment#errorChildProcess A system error occurred (spawn /bin/bash ENOENT)
> [main 2024-12-15T10:26:05.837Z] Unable to resolve your shell environment: A system error occurred (spawn /bin/bash ENOENT)
> [2:1215/102607.755188:ERROR:service_worker_storage.cc(2016)] Failed to delete the database: Database IO error
> [41:1215/102609.838085:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
> [main 2024-12-15T10:26:09.998Z] ptyHost was unable to resolve shell environment Error: Unable to resolve your shell environment: A system error occurred (spawn /bin/bash ENOENT)
>     at file:///usr/share/codium/resources/app/out/main.js:46:27862
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async file:///usr/share/codium/resources/app/out/main.js:33:116220
> 
> 
> "
```

**Comment by ihateprogramming88** [comment]
![image](https://github.com/user-attachments/assets/26e52b43-8d31-45b7-8382-05988f188e29)

**Comment by unforgivablesin** [comment]
Next time put them in code blocks so its easier to read
